In [1]:
import numpy as np

# 1. Đọc dữ liệu từ 2 file CSV
file_sem1 = "semester1_scores.csv"
file_sem2 = "semester2_scores.csv"

# Dùng genfromtxt để xử lý dòng thiếu/hỏng
data_sem1 = np.genfromtxt(file_sem1, delimiter=",", dtype=None, encoding="utf-8", skip_header=1)
data_sem2 = np.genfromtxt(file_sem2, delimiter=",", dtype=None, encoding="utf-8", skip_header=1)

# 2. Kiểm tra typr, shape
print("Semester 1 dtype:", data_sem1.dtype)
print("Semester 1 shape:", data_sem1.shape)

print("Semester 2 dtype:", data_sem2.dtype)
print("Semester 2 shape:", data_sem2.shape)

# 3. Tách thành các mảng con
# Giả sử file có format:
# sid, midterm, final, attendance_hw

sid1  = data_sem1[:, 0].astype(str)
mid1  = data_sem1[:, 1].astype(float)
final1 = data_sem1[:, 2].astype(float)
att1   = data_sem1[:, 3].astype(float)

sid2  = data_sem2[:, 0].astype(str)
mid2  = data_sem2[:, 1].astype(float)
final2 = data_sem2[:, 2].astype(float)
att2   = data_sem2[:, 3].astype(float)

# 4. Xuất 5 giá trị đầu/cuối
print("\nSemester 1 - 5 dòng đầu:")
print(data_sem1[:5])

print("\nSemester 1 - 5 dòng cuối:")
print(data_sem1[-5:])

print("\nSemester 2 - 5 dòng đầu:")
print(data_sem2[:5])

print("\nSemester 2 - 5 dòng cuối:")
print(data_sem2[-5:])

# 5. Kiểm tra lỗi / thiếu dữ liệu / định dạng sai
def check_data_errors(data, name):
    print(f"\n--- Kiểm tra lỗi dữ liệu {name} ---")

    # Kiểm tra giá trị NaN
    if np.isnan(data[:,1:].astype(float)).any():
        print(" Có giá trị NaN trong bảng.")
    else:
        print(" Không có giá trị NaN.")

    # Điểm phải nằm trong 0–100
    numeric = data[:,1:].astype(float)
    if ((numeric < 0) | (numeric > 100)).any():
        print(" Có điểm nằm ngoài khoảng 0–100.")
    else:
        print(" Tất cả điểm trong khoảng hợp lệ.")

check_data_errors(data_sem1, "Semester 1")
check_data_errors(data_sem2, "Semester 2")

print("\n>>> DỮ LIỆU ĐÃ LÀM SẠCH HOÀN TẤT.")
#

Semester 1 dtype: float64
Semester 1 shape: (150, 4)
Semester 2 dtype: float64
Semester 2 shape: (150, 4)

Semester 1 - 5 dòng đầu:
[[1001.      5.87    9.      6.21]
 [1002.      8.75    5.32    8.13]
 [1003.      7.66    4.8     8.16]
 [1004.      6.99    6.69    8.55]
 [1005.      4.78    9.42    8.9 ]]

Semester 1 - 5 dòng cuối:
[[1146.      4.18    6.87    9.79]
 [1147.      7.05    8.23    9.94]
 [1148.      6.51    5.19    9.01]
 [1149.      4.26    7.43    7.51]
 [1150.      5.39    4.47    6.33]]

Semester 2 - 5 dòng đầu:
[[1001.      7.89    4.93    6.47]
 [1002.      6.79    5.53    9.76]
 [1003.      6.12    4.97    8.51]
 [1004.      8.53    4.49    7.34]
 [1005.      4.56    4.66    6.56]]

Semester 2 - 5 dòng cuối:
[[1146.      6.37    8.95    6.82]
 [1147.      7.34    6.11    7.17]
 [1148.      4.86    6.99    9.59]
 [1149.      4.96    8.99    6.05]
 [1150.      4.2     7.43    6.34]]

--- Kiểm tra lỗi dữ liệu Semester 1 ---
 Không có giá trị NaN.
 Tất cả điểm trong k